import { ReactNode } from "react";
import { VariantProps, tv } from "tailwind-variants";

import "./globals.css";

import Spacer from "components/atom/Spacer";
import Font from "components/atom/Font";
import GridPaper from "./GridPaper";
import URLProvider from "./_url/URLProvider";
import URLCard from "./_url/URLCard";
import MainCard from "./_main/MainCard";

export const metadata = {
  title: "Router Sample",
  description: "Generated by create next app",
};

const layout = tv({
  base: "h-screen w-full text-slate-400",
  variants: {},
  defaultVariants: {},
});

type Variant = VariantProps<typeof layout>;

interface Props extends Variant {
  children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ja">
      <body className={layout()}>
        <Font>
          <GridPaper>
            <Spacer space="global">
              <URLProvider>
                <div className="flex flex-col gap-y-8">
                  <URLCard />
                  <MainCard>{children}</MainCard>
                </div>
              </URLProvider>
            </Spacer>
          </GridPaper>
        </Font>
      </body>
    </html>
  );
}
